# You should enable this to get bug fixes and receive support
auto-update: true

# Whether to enable the debug logs
debug: false

# The default language of the plugin
# SlimefunTranslation is supported.
lang: en

# Balance options
balance:
  # The cost multiplier for singularity crafting
  # Range: 0.0 to 1000.0
  singularity-cost-multiplier: 1.0

  # Can Gear Transformer transform slimefun gear's material.
  # Diamond tools can already be upgraded to netherite,
  # but some addon developers do not want their gear to be transformable, so change this at your own risk.
  allow-sf-item-transform: false

  # Whether to enable researches
  enable-researches: false

# Resource synthesizer options
resource-synthesizer:
  # Each line represents a recipe.
  # format: input1,input2,output,amount
  # Use English comma (,) to separate the arguments.
  # The 4th argument is the amount of output item, default is 1, can be omitted.
  #
  # The input item must be a singularity that can be constructed from a singularity constructor.
  # (meaning fortune, magic, earth, and metal singularity cannot be used as ingredient)
  # The common ID prefix for input item(IE_) is not needed.
  #
  # For the output item, you MUST use the full ID of the item. (for infinity expansion 2 items, they are all prefixed IE_)
  # If the recipe output is not a valid Slimefun item, the recipe will be ignored.
  recipes:
    - 'IRON_SINGULARITY,COAL_SINGULARITY,REINFORCED_ALLOY_INGOT,32'
    - 'DIAMOND_SINGULARITY,COAL_SINGULARITY,CARBONADO,16'
    - 'GOLD_SINGULARITY,EMERALD_SINGULARITY,BLISTERING_INGOT_3,16'
    - 'COPPER_SINGULARITY,ZINC_SINGULARITY,ELECTRO_MAGNET,64'
    - 'IRON_SINGULARITY,QUARTZ_SINGULARITY,SOLAR_PANEL,64'

# Mob simulation options
mob-simulation:

  # The amount of runs required to output once (affected by tick rate)
  # Range: 1 to 3600
  output-interval: 20

  # The experience multiplier for mob simulation
  # Range: 0.0 to 1000.0
  exp-multiplier: 1.0

# Quarry options
quarry:
  # The amount of runs required to output once (affected by tick rate)
  # Range: 1 to 3600
  output-interval: 10

  # The product pool of all the quarries
  # There are 3 world environments: normal, nether, the_end
  # A quarry's products are determined by the environment it is in.
  # The quarry wiki page has a detailed explanation of how the quarry works, it may help you understand the pool.
  #
  # All the item IDs must be a valid Material, or a valid Slimefun item ID.
  #
  # Due to how the config file is processed, you cannot remove existing fields.
  # If you want to "remove" an item from the pool, set its weight to 0.
  pools:
    normal:
      base-product: COBBLESTONE
      products:
        COAL: 4
        COPPER_INGOT: 2
        IRON_INGOT: 1
        GOLD_INGOT: 1
        REDSTONE: 1
        LAPIS_LAZULI: 1
        EMERALD: 1
        DIAMOND: 1
    nether:
      base-product: NETHERRACK
      products:
        GOLD_INGOT: 3
        QUARTZ: 1
        NETHERITE_INGOT: 1
    the_end:
      base-product: END_STONE
      products:
        OBSIDIAN: 1

  # The chance (0 to 1) of an oscillator activating each time a material would be produced
  # The materials listed here will be registered as oscillators.
  # The key must be a valid material ID, or a valid Slimefun item ID.
  oscillators:
    LAPIS_LAZULI: .5
    DIAMOND: .5
    REDSTONE: .5
    QUARTZ: .5
    EMERALD: .5

# The maximum possible level of every enchantment in advanced anvil
# all the keys are the key part of an Enchantment's NamespacedKey
# Enchantment: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
# You can add any enchantments, but cannot remove.
# If you want to "remove" an enchantment, set its level to 0, it will be read as not set, thus will have its vanilla limit.
# Enchantments not defined here will have the vanilla level limit.
#
# after 1.20.5, bukkit renamed the naming of Enchantment enum, so the name is the same as the key part except case.
# so, you only need to turn the Enchantment's name into lowercase.
# e.g. FIRE_ASPECT -> fire_aspect
advanced-anvil:
  max-levels:
    sharpness: 9
    bane_of_arthropods: 9
    smite: 9
    protection: 10
    fortune: 6
    efficiency: 7
    fire_aspect: 6
    power: 7
    thorns: 13
    looting: 6
    unbreaking: 13

# Defines the enchantment levels of infinity gears.
#
# `unbreakable` is a boolean value that determines whether the gear is unbreakable.
# You can add new enchantments, but cannot remove enchantment fields, the plugin will fill all missing fields.
# To disable an existing enchantment, set its level to 0.
#
# This only affects new gears, not existing ones.
# protection caps out at 20 levels across all 4 pieces of gear. So 10+10+10+10 is still the same as 5+5+5+5.
infinity-gear:
  sword:
    unbreakable: true
    enchantments:
      sharpness: 20
      looting: 10
      fire_aspect: 10
  pickaxe:
    unbreakable: true
    enchantments:
      efficiency: 40
      fortune: 20
  shovel:
    unbreakable: true
    enchantments:
      efficiency: 40
      silk_touch: 10
  axe:
    unbreakable: true
    enchantments:
      efficiency: 40
      sharpness: 20
      fire_aspect: 10
      looting: 0
      silk_touch: 0
  hoe:
    unbreakable: true
    enchantments:
      efficiency: 40
      fortune: 20
      silk_touch: 0
  fishing_rod:
    unbreakable: true
    enchantments:
      luck_of_the_sea: 10
      lure: 10
  bow:
    unbreakable: true
    enchantments:
      power: 10
      flame: 10
      infinity: 10
      punch: 0
  crossbow:
    unbreakable: true
    enchantments:
      power: 10
      punch: 0
      piercing: 5
      multishot: 10
      quick_charge: 5
  helmet:
    unbreakable: true
    effects:
      night_vision: 0
      conduit_power: 0
    enchantments:
      protection: 20
      aqua_affinity: 10
  chestplate:
    unbreakable: true
    effects:
    enchantments:
      protection: 20
      thorns: 10
  leggings:
    unbreakable: true
    effects:
    enchantments:
      protection: 20
      thorns: 10
  boots:
    unbreakable: true
    effects:
    enchantments:
      protection: 20
      feather_falling: 0
      thorns: 0
  shield:
    unbreakable: true
    effects:
    enchantments:
      protection: 20
      thorns: 10

## Some InfinityExpansion2 items have their extra config options in Items.yml, check there for more information.
